---
# tasks file for prep_secrets

- name: make sure {{ credential_store }} is available
  file: 
    name: '{{ credential_store }}'
    owner: root
    group: "{{ ansible_env.SUDO_USER | default('root') }}"
    mode:  0775
    state: directory
  delegate_to: localhost

- name: generate db passwd if nc_db_passwd is empty
  set_fact: 
    nc_db_passwd: "{{ lookup('password', '{{ credential_store }}/database_secret chars=ascii_letters,digits length=32') }}"
  when: nc_db_passwd == ''
