---
# tasks file for prep_ufw

- name: include os specific tasks
  include_tasks: "{{ ansible_distribution }}.yml"

- name: Configuring port/protocol/network rules
  ufw:
    delete: "{{ item.delete | default(omit) }}"
    direction: "{{ item.direction | default(omit) }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
    from_port: "{{ item.from_port | default(omit) }}"
    insert: "{{ item.insert | default(omit) }}"
    interface: "{{ item.interface | default(omit) }}"
    log: "{{ item.log | default(omit) }}"
    logging: "{{ item.logging | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    policy: "{{ item.policy | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    proto: "{{ item.proto | default(omit) }}"
    rule: "{{ item.rule | default('allow') }}"
    state: "{{ item.state | default(omit) }}"
    to_ip: "{{ item.to_ip | default(omit) }}"
    to_port: "{{ item.to_port | default(omit) }}"
  with_items: "{{ ufw_rules }}"

- name: Configuring application rules
  ufw:
    name: "{{ item.name }}"
    rule: "{{ item.rule if item.rule is defined else 'allow' }}"
    from_ip: "{{ item.from_ip | default(omit)  }}"
  with_items: "{{ ufw_applications }}"

- name: Configuring firewall
  template:
    src: etc_default_ufw.j2
    dest: /etc/default/ufw
    owner: root
    group: root
    mode: 0644
  notify: reload ufw
  
- name: Configuring service
  ufw:
    state: "{{ ufw_state }}"
    logging: "{{ ufw_logging }}"
    
- name: Enabling firewall
  ufw:
    state: enabled
  when: ufw_reset|bool

- name: start ufw
  systemd:
    name:  ufw
    state: started
    enabled: true
  when: ufw_state == 'enabled'