---
# vars file for prep_os

service_path:
  CentOS: '/usr/lib/systemd/system'
  Fedora: '/usr/lib/systemd/system'
  Amazon: '/usr/lib/systemd/system'
  Ubuntu: '/lib/systemd/system'
  Debian: '/lib/systemd/system'
