---
# Debian related OS tasks

- name: add nginx key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: add additional debian repos
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - 'deb http://nginx.org/packages/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx'
    - 'deb-src http://nginx.org/packages/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx'

- name: apt dist-upgrade
  apt:
    upgrade: dist
    autoremove: true

- name: install additional packages
  apt:
    name:
    - nginx
    - python-pip
    - python-netaddr
    autoremove: true
    allow_unauthenticated: true
    state: latest
