---
# Ubuntu related OS tasks

- name: Add an apt key by id for PPA for NGINX Mainline with HTTP/2
  apt_key:
    keyserver: hkps://keyserver.ubuntu.com
    id: 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C
    state: present

- name: add additional repos for PPA for NGINX Mainline with HTTP/2
  apt_repository:
    repo: 'deb http://ppa.launchpad.net/ondrej/nginx-mainline/ubuntu {{ ansible_distribution_release }} main'
    validate_certs: true
    update_cache: true
    state: present

- name: remove standard nginx
  apt:
    name:
      - nginx-full
    state: absent

- name: apt dist-upgrade
  apt:
    upgrade: dist
    autoremove: true

- name: install additional packages
  apt:
    name: [nginx-extras,openssl]
    autoremove: true
    state: latest

- name: install needed packages
  apt:
    name:
      - python-pip
      - python-netaddr
    state: latest
