---
# tasks file for onlyoffice installation

- name: build onlyoffice docker image for selfsigned certificates
  docker_image:
    source: build
    name:   onlyoffice/documentserver
    build:
      path: "{{ role_path }}/docker"
      pull: yes
    rm:     true
  when: (tls_certificate_type == 'selfsigned') or tls_certificate_test

- name: start a onlyoffice container
  docker_container:
    name: onlyoffice
    image: onlyoffice/documentserver
    state: started
    restart: yes
    restart_policy: always
    interactive: true
    tty: yes
    ports:
     - "{{ onlyoffice_ssl_port }}:443"
    env:
      ONLYOFFICE_HTTPS_HSTS_ENABLED: "{% if (tls_certificate_type == 'selfsigned') or tls_certificate_test %}false{% else %}true{% endif %}"
      SSL_SELFSIGNED_CERTIFICATE: "{% if (tls_certificate_type == 'selfsigned') or tls_certificate_test %}true{% else %}false{% endif %}"
      JWT_ENABLED:  'true'
      JWT_SECRET:   "{{ lookup('password', '{{ credential_store }}/onlyoffice_secret chars=ascii_letters,digits length=32') }}"
    volumes:
    - "{{ tls_certificate_key }}:/var/www/onlyoffice/Data/certs/onlyoffice.key:ro"
    - "{{ tls_certificate_file }}:/var/www/onlyoffice/Data/certs/onlyoffice.crt:ro"
    - "{{ tls_certificate_fullchain }}:/var/www/onlyoffice/Data/certs/ca-certificates.pem:ro"
    - "{{ tls_certificate_directory }}/dhparam.pem:/var/www/onlyoffice/Data/certs/dhparam.pem:ro"

- name: prune container and images
  docker_prune:
    containers: true
    images: true

- name: open special web server ports
  ufw:
    rule: allow
    port: "'{{ onlyoffice_ssl_port }}'"
    proto: tcp
  when: ansible_os_family == 'Debian'

- name: open firewall ports {{ nextcloud_web_port }}/{{ nextcloud_ssl_port }}
  firewalld:
    port: "{{ onlyoffice_ssl_port }}/tcp"
    permanent: true
    immediate: false
    state: enabled
  when: ansible_os_family == 'RedHat'
